### ISSUE TITLE
ai_milp: Infeasible Model

### ISSUE THREAD

**Issue by cherrywoods** [eth-sri/eran#61]
In the latest revision some code has been added to ai_milp concerning handling infeasible models. 
The code now sometimes fails when I run it, with an assertion violation related to this, namely that a model is infeasible (status code 3).

What does this mean concretely? Is there any way to treat this?
For the attached onnx network I encounter this error if verifying ACAS Xu property 2:
```shell
python . --netname acasxu_2_9_modified.onnx --specnumber 2 --domain deeppoly --complete True --dataset acasxu
```
> AcasXu property 2 Failed for Box 0 out of 1 because of an exception  Infeasible model encountered. Model status 3

[test_network.zip](https://github.com/eth-sri/eran/files/6218173/test_network.zip)

**Comment by mnmueller** [comment]
@cherrywoods thank you for your interest in ERAN.

We have looked into your issue but unfortunately can't reproduce this error. 

We do however encounter the following different error:
```
[ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid rank for input: input.1 Got: 1 Expected: 2 Please fix either the inputs or the model.
```

This is caused by your model expecting a batch dimension, while the model is fed an input without one. We were able to resolve this issue by replacing Line 211 in tf_verify/__main__.py (`inputs = [(((dim_samples - i) * specLB + i * specUB) / dim_samples) for i in range(dim_samples + 1)]`)
with
```
inputs = [(((dim_samples - i) * specLB + i * specUB) / dim_samples).reshape(1,-1) for i in range(dim_samples + 1)]
```
With this change, the model runs without issue for us.
We have not committed this as this change might break things for other networks.

Cheers,
Mark

**Comment by cherrywoods** [comment]
Hi Mark, 
thank you for looking into this. I am sorry, I made that change regarding the batch dimension in my fork. I thought I had not made any other changes that would impair functionality, but apparently I have, so sorry for wasting your time...

Kind regards,
David

**Comment by cherrywoods** [comment]
In case of the rare event that this did come up for anyone else: My dependencies were not up to date...
