### ISSUE TITLE
Infeasible Model Error

### ISSUE THREAD

**Issue by cherrywoods** [eth-sri/eran#74]
Dear ERAN Developers,
When running the following command to verify the attached modified ACAS XU 3,9 network, the program exists with an exception, due to an Inseasible Model while performing MIP solving (Gurobi exit status 3):
```shell
python3 . --dataset acasxu --domain deeppoly --complete True --spec 2 --netname acas_xu_3_9_mod_from_nnet.onnx
```

> AcasXu property 2 Failed for Box 0 out of 1 because of an exception  
Infeasible model encountered. Model status 3

This error occurs for me after running for about 160 seconds. I opened a similar issue in the past, which was not properly justified. This time I checked that this error occurs by running ERAN at the latest commit inside a virtual machine, so I hope you will be able to reproduce the error this time. 

The virtual machine runs Ubuntu 18.04 (but the error also occurred for me on Ubuntu 20.04). The onnx file is created using the [NNet Onnx export tool](https://github.com/sisl/NNet/tree/master/converters) so that the file can be read by `onnx==1.5.0`. The .nnet file is contained in the attached zip file as well.
The zip file also contains another onnx file generated with pytorch that can only be used with a newer onnx version (acas_xu_3_9_mod.onnx). Also for this file I am getting the Infeasible Model error. 

 [acas_xu_3_9_mod.zip](https://github.com/eth-sri/eran/files/6405191/acas_xu_3_9_mod.zip)

Best regards,
David

**Comment by mnmueller** [comment]
Hello David,

Thanks for providing this interesting example. After looking into it, it seems like the exception is triggered for a specific split of the input domain. It can be triggered outside of the parallel optimization adding the following to lines before the first call to eran.analyze_box:
```        
failed_already = Value('i', 1)
acasxu_recursive([0.6399288843500001, 0.011363636363636423, -0.37499999999999994, 0.47500000000000003, -0.46249999999999997], [0.6798577687, 0.02272727272727279, -0.36249999999999993, 0.5, -0.45], 10, 10)
``` 
Doing so and checking, when the model becomes infeasible I found that this happens only when the optimization objective is added (GUROBI treats problems without objective as feasibility problems). 
Further, when changing the sign of the second term in the optimization objective (or simply choosing a different one) the model remains feasible.
As the optimization objective should never change the feasibility of a model, I assume that this issue is due to (numerical) problems with Gurobi.

I was able to avoid this by increasing the "Cutoff" parameter in line 359 of ai_milp (https://github.com/eth-sri/eran/blob/master/tf_verify/ai_milp.py#L859) to 0.1:
```
model.setParam(GRB.Param.Cutoff, 0.1)
```

Using this I can verify the property for the network you provided.

Cheers,
Mark

**Comment by cherrywoods** [comment]
Hello Mark,
Thanks for debugging this! 
Adjusting the Cutoff also solves the issue for me. I think I will write some code that will dynamically increase the Cutoff bound if such an error occurs, because it came up a few times for me, I think in 2 out of 100 runs or so. 

Thanks again for looking into this and for the great support :+1::+1:!
Cheers,
David
